<a href="https://colab.research.google.com/github/Kateriiina/Lesson/blob/main/%D0%9F%D0%B5%D1%80%D0%B2%D0%B0%D1%8F_%D1%87%D0%B0%D1%81%D1%82%D1%8C_%D0%BB%D0%B0%D0%B1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB

from sklearn.datasets import load_iris

In [2]:
# Завантаження даних
iris = load_iris()
X = iris.data
y = iris.target

# Розділення даних на тренувальний та тестовий набори
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [3]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Наївний байєсівський класифікатор - гаусівський
gnb = GaussianNB()

#тренування моделі
gnb.fit(X_train, y_train)

# Прогнозування класів для тестового набору
y_pred = gnb.predict(X_test)

print("Score at the training set: {:.3f}".format(gnb.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(gnb.score(X_test, y_test)))

print(classification_report(y_test, y_pred, target_names = iris.target_names))
print(confusion_matrix(y_test, y_pred))

Score at the training set: 0.946
Score at the training set: 1.000
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       1.00      1.00      1.00        11
   virginica       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


In [5]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Наївний поліноміальний класифікатор
gnb_M = MultinomialNB()

#тренування моделі
gnb_M.fit(X_train, y_train)

# Прогнозування класів для тестового набору
y_pred_M = gnb_M.predict(X_test)

print("Score at the training set: {:.3f}".format(gnb_M.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(gnb_M.score(X_test, y_test)))

print(classification_report(y_test, y_pred_M, target_names = iris.target_names))
print(confusion_matrix(y_test, y_pred_M))

Score at the training set: 0.964
Score at the training set: 0.974
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       0.92      1.00      0.96        11
   virginica       1.00      0.92      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38

[[15  0  0]
 [ 0 11  0]
 [ 0  1 11]]


In [6]:
#Логістична регресія при C = 0.1
lr1 = LogisticRegression(C = 0.1, max_iter = 95)
lr1.fit(X_train, y_train)

print("Логістична регресія при C = 0.1")
print("Score at the training set: {:.3f}".format(lr1.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(lr1.score(X_test, y_test)))
print()

#Логістична регресія при C = 0.5
lr2 = LogisticRegression(C = 0.5, max_iter = 95)
lr2.fit(X_train, y_train)

print("Логістична регресія при C = 0.5")
print("Score at the training set: {:.3f}".format(lr2.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(lr2.score(X_test, y_test)))
print()

#Логістична регресія при C = 1.0
lr3 = LogisticRegression(C = 1.0, max_iter = 95)
lr3.fit(X_train, y_train)

print("Логістична регресія при C = 1.0")
print("Score at the training set: {:.3f}".format(lr3.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(lr3.score(X_test, y_test)))
print()

#Логістична регресія при C = 10.0
lr4 = LogisticRegression(C = 10.0, max_iter = 95)
lr4.fit(X_train, y_train)

print("Логістична регресія при C = 10.0")
print("Score at the training set: {:.3f}".format(lr4.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(lr4.score(X_test, y_test)))
print()

Логістична регресія при C = 0.1
Score at the training set: 0.946
Score at the training set: 1.000

Логістична регресія при C = 0.5
Score at the training set: 0.964
Score at the training set: 1.000

Логістична регресія при C = 1.0
Score at the training set: 0.964
Score at the training set: 1.000

Логістична регресія при C = 10.0
Score at the training set: 0.991
Score at the training set: 1.000



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [10]:
# Прогнозування класів для тестового набору
y_pred1 = lr1.predict(X_test)

print(classification_report(y_test, y_pred, target_names = iris.target_names))
print(confusion_matrix(y_test, y_pred1))
print()

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       1.00      1.00      1.00        11
   virginica       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]



In [8]:
# k-найближчих сусідів - euclidean, n = 1
knn2 = KNeighborsClassifier(n_neighbors = 1, metric='euclidean')
knn2.fit(X_train, y_train)

print("k-найближчих сусідів - euclidean, n = 1")
print("Score at the training set: {:.3f}".format(knn2.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(knn2.score(X_test, y_test)))
print()

# k-найближчих сусідів - chebyshev, n = 1
knn3 = KNeighborsClassifier(n_neighbors=1, metric='chebyshev')
knn3.fit(X_train, y_train)

print("k-найближчих сусідів - chebyshev, n = 1")
print("Score at the training set: {:.3f}".format(knn3.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(knn3.score(X_test, y_test)))
print()

# k-найближчих сусідів - euclidean, n = 2
knn4 = KNeighborsClassifier(n_neighbors=2, metric='euclidean')
knn4.fit(X_train, y_train)

print("k-найближчих сусідів - euclidean, n = 2")
print("Score at the training set: {:.3f}".format(knn4.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(knn4.score(X_test, y_test)))
print()

# k-найближчих сусідів - euclidean, n = 3
knn5 = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
knn5.fit(X_train, y_train)

print("k-найближчих сусідів - euclidean, n = 3")
print("Score at the training set: {:.3f}".format(knn5.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(knn5.score(X_test, y_test)))
print()

# k-найближчих сусідів - euclidean, n = 4
knn6 = KNeighborsClassifier(n_neighbors=4, metric='euclidean')
knn6.fit(X_train, y_train)

print("k-найближчих сусідів - euclidean, n = 4")
print("Score at the training set: {:.3f}".format(knn6.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(knn6.score(X_test, y_test)))
print()

# k-найближчих сусідів - euclidean, n = 5
knn7 = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
knn7.fit(X_train, y_train)

print("k-найближчих сусідів - euclidean, n = 5")
print("Score at the training set: {:.3f}".format(knn7.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(knn7.score(X_test, y_test)))
print()

# k-найближчих сусідів - euclidean, n = 6
knn8 = KNeighborsClassifier(n_neighbors=6, metric='euclidean')
knn8.fit(X_train, y_train)

print("k-найближчих сусідів - euclidean, n = 6")
print("Score at the training set: {:.3f}".format(knn8.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(knn8.score(X_test, y_test)))
print()

# k-найближчих сусідів - euclidean, n = 7
knn9 = KNeighborsClassifier(n_neighbors=7, metric='euclidean')
knn9.fit(X_train, y_train)

print("k-найближчих сусідів - euclidean, n = 7")
print("Score at the training set: {:.3f}".format(knn9.score(X_train, y_train)))
print("Score at the training set: {:.3f}".format(knn9.score(X_test, y_test)))

k-найближчих сусідів - euclidean, n = 1
Score at the training set: 1.000
Score at the training set: 1.000

k-найближчих сусідів - chebyshev, n = 1
Score at the training set: 1.000
Score at the training set: 1.000

k-найближчих сусідів - euclidean, n = 2
Score at the training set: 0.964
Score at the training set: 1.000

k-найближчих сусідів - euclidean, n = 3
Score at the training set: 0.946
Score at the training set: 1.000

k-найближчих сусідів - euclidean, n = 4
Score at the training set: 0.964
Score at the training set: 1.000

k-найближчих сусідів - euclidean, n = 5
Score at the training set: 0.964
Score at the training set: 1.000

k-найближчих сусідів - euclidean, n = 6
Score at the training set: 0.964
Score at the training set: 1.000

k-найближчих сусідів - euclidean, n = 7
Score at the training set: 0.973
Score at the training set: 1.000


In [11]:
# Прогнозування класів для тестового набору
knn2_pred = knn2.predict(X_test)

print(classification_report(y_test, y_pred, target_names = iris.target_names))
print(confusion_matrix(y_test, knn2_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       1.00      1.00      1.00        11
   virginica       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]
